### ISSUE TITLE
Adding maintainers

### ISSUE THREAD

**Issue by smmaurer** [conda-forge/urbanaccess-feedstock#2]
Hi @ocefpaf, 

I just uploaded a new release of UrbanAccess to PyPI, so the bot should be opening a PR here soon. Could you add me and @sablanchard as additional maintainers before merging it? (Or if it's easier, you could ignore the bot's PR and I can open a separate one with those changes.)

The new release is a compatibility update to add support for GeoPy 2.0+ and Pandas 1.0+. None of the dependencies or licensing should have changed.

https://github.com/UDST/urbanaccess/pull/66
https://pypi.org/project/urbanaccess/0.2.1/#files

Thanks!

**Comment by ocefpaf** [comment]
Done in #3 

Thanks!

**Comment by smmaurer** [comment]
Thanks so much!

**Comment by ocefpaf** [comment]
My pleasure!
